export const rows = [
  {
    id: 1,
    full_name: "Korrie O'Crevy",
    post: "Nuclear Power Engineer",
    email: "kocrevy0@thetimes.co.uk",
    city: "Krasnosilka",
    start_date: "09/23/2016",
    salary: 23896.35,
    age: "61",
    experience: "1 Year",
    status: 2,
  },
  {
    id: 7,
    full_name: "Eileen Diehn",
    post: "Environmental Specialist",
    email: "ediehn6@163.com",
    city: "Lampuyang",
    start_date: "10/15/2017",
    salary: 18991.67,
    age: "59",
    experience: "9 Years",
    status: 3,
  },
  {
    id: 11,
    full_name: "De Falloon",
    post: "Sales Representative",
    email: "dfalloona@ifeng.com",
    city: "Colima",
    start_date: "06/12/2018",
    salary: 19252.12,
    age: "30",
    experience: "0 Year",
    status: 4,
  },
  {
    id: 3,
    full_name: "Stella Ganderton",
    post: "Operator",
    email: "sganderton2@tuttocitta.it",
    city: "Golcowa",
    start_date: "03/24/2018",
    salary: 13076.28,
    age: "66",
    experience: "6 Years",
    status: 5,
  },
]
